version: '3'
services:
  nginx:
    container_name: simple-nginx
    image: nginx:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - backup

  app1:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080"
    environment:
      - NAME=Arkadiy
    command: mvn clean spring-boot:run

  app2:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    environment:
      - NAME=Dmitriy
    command: mvn clean spring-boot:run

  backup:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    environment:
      - NAME=Backup
    command: mvn clean spring-boot:run